name: release

on:
  push:
    branches:
    - main

env:
  AWS_REGION: us-west-2
  AWS_ROLE: arn:aws:iam::270074865685:role/terraform-module-ci-test
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  ACME_SERVER_URL: https://acme-v02.api.letsencrypt.org/directory

permissions: {}

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    timeout-minutes: 60
    container:
      image: ghcr.io/rancher/ci-image/nix:20260603-18
      options: --user suse
    steps:
      - name: Fix Runner Permissions
        shell: bash
        run: |
          sudo chown -R "$(whoami)" /home/runner
          sudo chmod -R 0770 /home/runner

      - name: 'Release Please'
        # https://github.com/googleapis/release-please-action/releases
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release-please
        with:
          release-type: terraform-module

      - name: Free Disk Space Before Test
        shell: bash
        run: |
          bash .github/workflows/scripts/nix-run.sh "bash .github/workflows/scripts/free-disk-space.sh"

      - name: 'Comment PR e2e wait'
        # https://github.com/actions/github-script/releases
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        if: steps.release-please.outputs.pr
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const scriptPath = `${process.env.GITHUB_WORKSPACE}/.github/workflows/scripts/pr-e2e-wait.js`;
            const { default: script } = await import(scriptPath);
            context.payload.pull_request = { number: ${{ fromJson(steps.release-please.outputs.pr).number }} };
            await script({ github, context });

      - name: Checkout
        if: steps.release-please.outputs.pr
        shell: bash
        run: |
          sudo chown -R "$(whoami)" . "$HOME"
          sudo git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git init .
          git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git"
          git fetch --tags --force origin
          git fetch origin "+refs/heads/*:refs/remotes/origin/*"
          git fetch origin "+refs/pull/${{ github.event.number }}/merge:refs/remotes/pull/${{ github.event.number }}/merge"
          git checkout "${{ github.sha }}"

      - name: 'Configure AWS Credentials'
        id: aws-creds
        # https://github.com/aws-actions/configure-aws-credentials/releases
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        if: steps.release-please.outputs.pr
        with:
          role-to-assume: ${{env.AWS_ROLE}}
          role-session-name: ${{github.run_id}}
          aws-region: ${{env.AWS_REGION}}
          role-duration-seconds: 7200 # 2 hours
          output-credentials: true

      - name: Run Tests
        if: steps.release-please.outputs.pr
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.aws-creds.outputs.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.aws-creds.outputs.aws-secret-access-key }}
          AWS_SESSION_TOKEN: ${{ steps.aws-creds.outputs.aws-session-token }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITHUB_OWNER: rancher
          IDENTIFIER: ${{github.run_id}}
          ZONE: ${{secrets.ZONE}}
          ACME_SERVER_URL: https://acme-v02.api.letsencrypt.org/directory
          RANCHER_INSECURE: false
        run: |
          bash .github/workflows/scripts/nix-run.sh "bash .github/workflows/scripts/execute-tests.sh"

      - name: 'Comment PR e2e pass'
        # https://github.com/actions/github-script/releases
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        if: steps.release-please.outputs.pr
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const scriptPath = `${process.env.GITHUB_WORKSPACE}/.github/workflows/scripts/pr-e2e-pass.js`;
            const { default: script } = await import(scriptPath);
            context.payload.pull_request = { number: ${{ fromJson(steps.release-please.outputs.pr).number }} };
            await script({ github, context });
